language: ruby

git:
  submodules: false

env:
  - AWS_DEFAULT_REGION=us-east-2 
  
before_install:
  - echo "Installing AWS CLI"
  - pip install --upgrade --user awscli
  - echo "Installing Test Gems"

install: true

script:
  - aws cloudformation validate-template --template-body file://2zone-vpc-cloudformation.yml

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Cloudformation Template Validated"
